FROM gcc:4.9
COPY . /client
WORKDIR /client/
# RUN chmod +x generate_random.sh && ./generate_random.sh
RUN dd if=/dev/urandom of=random.bin bs=10000 count=1
RUN gcc -o udp-client udp-client.c
ENTRYPOINT ["./udp-client"]